add-security-merge-to-master
alwayswannajava/Online-Book-Store pull request #10
Opened 2024-10-08 14:08 UTC by alwayswannajava

2024-10-08 14:28 UTC, Elena-Bruyako requested changes
see comments

2024-10-08 14:28 UTC, Elena-Bruyako commented on src/main/java/com/spring/onlinebookstore/security/CustomUserDetailsService.java
> +                .orElseThrow(() -> new UsernameNotFoundException(username));
provide informative message

```suggestion
                .orElseThrow(() -> new EntityNotFoundException(username));
```

2024-10-08 14:28 UTC, Elena-Bruyako commented on src/main/resources/db/changelog/changes/02-create-users-table.yaml
> +                  name: role_id
remove, user doesn't have role id column

2024-10-09 08:08 UTC, ahoienko approved these changes
Good job!

2024-10-09 11:36 UTC, merged