develop-book-category-tests-merge-to-master
alwayswannajava/Online-Book-Store pull request #17
Opened 2024-10-31 19:11 UTC by alwayswannajava

![image](https://github.com/user-attachments/assets/b79b60c5-9a48-495a-8fa7-904cf360a8cc)

2024-11-01 09:57 UTC, ahoienko requested changes
Nice, left minor comments

2024-11-01 09:57 UTC, ahoienko commented on src/test/java/com/spring/onlinebookstore/service/book/CategoryServiceTest.java
> +        verify(categoryRepository, times(1)).findById(CORRECT_CATEGORY_ID);
Times 1 is set by default

2024-11-01 09:57 UTC, ahoienko commented on src/test/resources/database/scripts/book/remove-book-test-data.sql
> +
Please remove redundant empty lines (check other scripts as well)

2024-11-01 09:57 UTC, ahoienko commented on src/test/java/com/spring/onlinebookstore/service/book/CategoryServiceTest.java
> +        assertThrows(EntityNotFoundException.class, () ->
Please check error message as well

2024-11-01 13:36 UTC, Elena-Bruyako requested changes
some comments

2024-11-01 13:36 UTC, Elena-Bruyako commented on src/test/java/com/spring/onlinebookstore/Constants.java
> +public final class Constants {
it's better to replace to util package

2024-11-01 13:36 UTC, Elena-Bruyako commented on src/test/java/com/spring/onlinebookstore/controller/BookControllerTest.java
> +    private void initDto() {
create TestUtil class and generate all test data there by using static methods
for all tests

2024-11-02 09:48 UTC, okuzan approved these changes

2024-11-02 20:29 UTC, merged