merge develop-controller to master
alwayswannajava/Online-Book-Store pull request #2
Opened 2024-09-18 10:56 UTC by alwayswannajava

2024-09-18 12:22 UTC, Elena-Bruyako requested changes
see comments

2024-09-18 12:22 UTC, Elena-Bruyako commented on src/main/java/com/spring/onlinebookstore/controller/BookController.java
> +@RequestMapping("/books")
```suggestion
@RequestMapping("/books")
@RequiredArgsConstructor
```

2024-09-18 12:22 UTC, Elena-Bruyako commented on src/main/java/com/spring/onlinebookstore/controller/BookController.java
> +    }
```suggestion
```

2024-09-18 12:22 UTC, Elena-Bruyako commented on src/main/java/com/spring/onlinebookstore/dto/CreateBookRequestDto.java
> +    @Nonnull
```suggestion
    @NotBlank
```

2024-09-18 12:22 UTC, Elena-Bruyako commented on src/main/java/com/spring/onlinebookstore/dto/CreateBookRequestDto.java
> +    @Nonnull
```suggestion
    @NotBlank
```

2024-09-18 12:22 UTC, Elena-Bruyako commented on src/main/java/com/spring/onlinebookstore/dto/CreateBookRequestDto.java
> +    @Nonnull
```suggestion
    @NotBlank
```

2024-09-18 12:22 UTC, Elena-Bruyako commented on src/main/java/com/spring/onlinebookstore/dto/CreateBookRequestDto.java
> +    @Nonnull
```suggestion
    @NotNull
```

2024-09-18 12:22 UTC, Elena-Bruyako commented on src/main/java/com/spring/onlinebookstore/model/Book.java
> +@NoArgsConstructor
```suggestion
```

2024-09-18 12:22 UTC, Elena-Bruyako commented on src/main/java/com/spring/onlinebookstore/repository/BookRepositoryImpl.java
> +@Repository
```suggestion
@Repository
@RequiredArgsConstructor
```

2024-09-18 12:22 UTC, Elena-Bruyako commented on src/main/java/com/spring/onlinebookstore/repository/BookRepositoryImpl.java
> +    }
```suggestion
```

2024-09-18 12:22 UTC, Elena-Bruyako commented on src/main/java/com/spring/onlinebookstore/repository/BookRepositoryImpl.java
> +        }
add catch

2024-09-18 12:22 UTC, Elena-Bruyako commented on src/main/java/com/spring/onlinebookstore/repository/BookRepositoryImpl.java
> +        }
add catch

2024-09-18 12:22 UTC, Elena-Bruyako commented on src/main/java/com/spring/onlinebookstore/service/BookServiceImpl.java
> +@Service
```suggestion
@Service
@RequiredArgsConstructor
```

2024-09-18 12:22 UTC, Elena-Bruyako commented on src/main/java/com/spring/onlinebookstore/service/BookServiceImpl.java
> +    }
```suggestion
```

2024-09-19 07:45 UTC, liliia-ponomarenko requested changes
Everything good but one important issue should be fixed 😉

2024-09-19 07:45 UTC, liliia-ponomarenko commented on src/main/java/com/spring/onlinebookstore/controller/BookController.java
> +
```suggestion
```

2024-09-19 07:45 UTC, liliia-ponomarenko commented on src/main/java/com/spring/onlinebookstore/dto/CreateBookRequestDto.java
> +        @Column(nullable = false, unique = true)
Use Column annotation only with fields of entity class. Also, you can validate ISBN format using annotation Pattern and some regex from google) 
```suggestion
        @NotBlank
```

2024-09-19 14:30 UTC, Elena-Bruyako approved these changes

2024-09-19 17:38 UTC, merged