develop-jpa-repo
alwayswannajava/Online-Book-Store pull request #3
Opened 2024-09-24 10:20 UTC by alwayswannajava

2024-09-24 13:50 UTC, Elena-Bruyako requested changes
see comments

2024-09-24 13:50 UTC, Elena-Bruyako commented on src/main/java/com/spring/onlinebookstore/service/BookServiceImpl.java
> +        update(book, updateBookRequestDto);
use MapStruct to update book

2024-09-24 13:50 UTC, Elena-Bruyako commented on src/main/java/com/spring/onlinebookstore/service/BookServiceImpl.java
> +    private void update(Book book, UpdateBookRequestDto updateBookRequestDto) {
remove method

2024-09-25 10:01 UTC, MentorMateAcademy approved these changes

2024-09-25 10:01 UTC, MentorMateAcademy commented on src/main/java/com/spring/onlinebookstore/model/Book.java
> +    private boolean isDeleted = false;
`@Column(nullable = false)
@Type(type = "org.hibernate.type.NumericBooleanType")
private boolean isDeleted = false;
`
try to use this way

2024-09-25 11:02 UTC, merged